channels:
- conda-forge
dependencies:
- numpy=1.24.1
- pip=22.3.1
- python=3.10.8
- pytorch=1.13.1
- pytorch_geometric=2.2.0
- pandas=1.5.2
- scipy=1.10.0
- tqdm=4.64.1
- rdkit=2022.09.3
- matplotlib=3.6.2
- ipykernel=6.20.1
- ca-certificates=2023.7.22
- certifi=2023.7.22
- openssl=3.1.1
- black=23.7.0
- wandb=0.13.9
- pytorch-lightning=1.8.1
- mypy=1.0.0
- seaborn=0.12.2
- cvxpy=1.3.1
- biotite=0.36.1
- biopandas=0.4.1
- pytorch_cluster
name: kinodata
